### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by dkerkow** [frankrowe/frankrowe.github.io#1]
Hi, I just discovered your page and wanted to subscribe to it via RSS, but found no feed. Did I miss it somehow or should I simply subscribe via GitHub?

**Comment by frankrowe** [comment]
Oh, I hadn't even thought of RSS. I'll definitely add a feed. In the meantime my twitter is @fsrowe, I usually tweet a link whenever I write a new post. Thanks for checking out the blog!

**Comment by frankrowe** [comment]
RSS feed added!

**Comment by dkerkow** [comment]
Great, thanks!
